export const AppActions = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET_COUNTER: "RESET_COUNTER",
  UPDATE_CART_ITEM_QUANTITY: "UPDATE_CART_ITEM_QUANTITY",
};
