export const AppActions = {
  //user
  AUTHENTICATED: "AUTHENTICATED",
  // SIGN_UP: "SIGN_UP",
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT",

  // Cart
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET_COUNTER: "RESET_COUNTER",
  UPDATE_CART_ITEM_QUANTITY: "UPDATE_CART_ITEM_QUANTITY",
  // Drawer
  TOGGLE_CART_DRAWER: "TOGGLE_CART_DRAWER",
  OPEN_CART_DRAWER: "OPEN_CART_DRAWER",
  CLOSE_CART_DRAWER: "CLOSE_CART_DRAWER",
  //Cursor On/off
  CURSOR_BLACK_ON: "CURSOR_BLACK_ON",
  CURSOR_BLACK_OFF: "CURSOR_BLACK_OFF",
};
